# GITLEAKS TEST FILE - FAKE SECRETS ONLY

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLL"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
GITHUB_TOKEN = "ghp_R2D2C3POR2D2C3POR2D2C3POR2D2C3PO1234"
DATABASE_URL = "postgresql://admin:SupssSecret123!@prod-db.internal:5432/mdms_prod"
