# GITLEAKS TEST - OPTION A - PR BLOCKING TEST

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
GITHUB_TOKEN = "ghp_R2D2C3POR2D2C3POR2D2C3POR2D2C3PO1234"
DATABASE_URL = "postgresql://admin:SuperSecret123!@prod-db.internal:5432/mdms_prod"
JWT_SECRET = "super-secret-jwt-signing-key-do-not-expose-1234567890abcdef"
